FROM mysql:5.5
ADD newmonk_common.sql /docker-entrypoint-initdb.d/newmonk_common.sql
ADD nLogger.sql /docker-entrypoint-initdb.d/nLogger.sql
ADD nLogger_heatmap.sql /docker-entrypoint-initdb.d/nLogger_heatmap.sql

