FROM nshou/elasticsearch-kibana
COPY elasticsearch.yml /home/elasticsearch/elasticsearch/config/
COPY kibana-index.tar.bz2 /home/elasticsearch/elasticsearch/data
WORKDIR /home/elasticsearch/elasticsearch/data
